print("Hello, world!")
a, b, c = "GOD", "IS", "REALLY GREAT AND ABOVE ALL, BLESS HIS HOLY NAME IN THE MIGHTY NAME OF JESUS CHRIST OUR LORD, SAVIOUR AND REDEEMER WHOM I LOVE AND ADORE BY HIS GRACE AND BY HIS GRACE IM SAVED, AMENNNNNNN"
print(a, b, c)
d, e, f =  "I", "LOVE", "JESUS CHRIST OF NAZARETH MY LORD AND SAVIOUR, BLESS HIS HOLY NAME IN JESUS MIGHTY NAME AMENNNNNNNNNNNNNNNNN"
print(d, e, f, a, b, c)
arithmetics = 2
aluminium, abia,abuja = "2k25", "is", "THE BEST YEAR OF MY LIFE"
print(abuja,abia, aluminium)
